apiVersion: v2
name: hpa-monitor
description: A Helm chart for HPA Monitor - Real-time Horizontal Pod Autoscaler monitoring dashboard
type: application
version: 0.1.2
appVersion: 0.1.2
home: https://github.com/younsl/hpa-monitor
sources:
  - https://github.com/younsl/hpa-monitor
maintainers:
  - name: younsl
    email: cysl@kakao.com
keywords:
  - kubernetes
  - hpa
  - monitoring
  - autoscaling
  - dashboard
annotations:
  category: Monitoring
